name: test workflow
on:
  push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to repository
        uses: actions/checkout@v4
      - name: setup go env
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: build go application
        run: go build ./cmd/server/main.go
      - name: run tests
        run: go test ./tests
